### ISSUE TITLE
When loading OptoDAS data with truncated files, the routine crashes instead of giving a warning

### ISSUE THREAD

**Issue by speleos** [xdas-dev/xdas#27]
The expected behaviour when dealing with truncated files would be to warn the user and ignore them.

https://github.com/xdas-dev/xdas/blob/3ef07141045ab7849b8dc27a72f2c1460425c37d/xdas/core/routines.py#L337

File ~/anaconda3/envs/simpledas/lib/python3.11/site-packages/xdas/core/routines.py:338, in open_mfdataarray(paths, dim, tolerance, squeeze, engine, verbose, **kwargs)
    336     else:
    337         iterator = as_completed(futures)
--> 338     objs = [future.result() for future in iterator]
    339 return combine_by_coords(objs, dim, tolerance, squeeze, None, verbose)

File ~/anaconda3/envs/simpledas/lib/python3.11/site-packages/xdas/core/routines.py:338, in <listcomp>(.0)
    336     else:
    337         iterator = as_completed(futures)
--> 338     objs = [future.result() for future in iterator]
    339 return combine_by_coords(objs, dim, tolerance, squeeze, None, verbose)

File ~/anaconda3/envs/simpledas/lib/python3.11/concurrent/futures/_base.py:449, in Future.result(self, timeout)
    447     raise CancelledError()
    448 elif self._state == FINISHED:
--> 449     return self.__get_result()
    451 self._condition.wait(timeout)
    453 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File ~/anaconda3/envs/simpledas/lib/python3.11/concurrent/futures/_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

OSError: Unable to synchronously open file (truncated file: eof = 5738496, sblock->base_addr = 0, stored_eof = 114278280)

**Comment by atrabattoni** [comment]
Thank you for reporting this. Indeed this routine fails when any of the file is corrupted/cannot be opened for any reason. A more user friendly solution would be to warn the user of the file that could not be opened. I will try to work on this in the next days.

**Comment by atrabattoni** [comment]
Please see the the related PR #29.
